# netlify.toml en la raíz de tu proyecto
[build]
  publish = "Frontend/html" # O "Frontend" si tu index.html está directamente en la carpeta Frontend
  command = "echo 'No build command needed for static site + functions'" # O tu comando de build si usas un framework JS

[functions]
  directory = "netlify/functions"

# Redirecciones para tus funciones de Asignatura
# Esto mapea tus peticiones /api/asignaturas a la función Asignatura.js
# y permite que las subrutas como /assignments o /register-student sean manejadas por Express.
[[redirects]]
  from = "/api/asignaturas/*"
  to = "/.netlify/functions/Asignatura/:splat" # :splat pasa el resto del path a la función
  status = 200
  force = true
