# netlify.toml

[build]
  publish = "Frontend" # Donde est치 tu HTML/CSS/JS del frontend
  command = "npm install && npm run copy-backend-for-functions" # Ajustamos el comando de build

[functions]
  directory = "netlify/functions" # Donde Netlify buscar치 el c칩digo de tus funciones

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # Redirige a tu funci칩n api.js
  status = 200
  force = true